# Generated by Django 2.2.6 on 2019-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('id_no', models.PositiveIntegerField()),
                ('division', models.CharField(choices=[('A&L', 'Arts and Law'), ('DES', 'Design'), ('ENG', 'Engineering'), ('SCI', 'Science'), ('M&C', 'Management and Commerce')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('reg_no', models.PositiveIntegerField()),
            ],
        ),
    ]
