# Generated by Django 2.2.6 on 2019-10-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('room_no', models.CharField(max_length=256)),
                ('block', models.CharField(max_length=256)),
                ('faculty_assigned', models.CharField(max_length=256)),
                ('course_code', models.CharField(max_length=256)),
                ('semester', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('school', models.CharField(max_length=256)),
                ('division', models.CharField(max_length=256)),
            ],
        ),
    ]
