# Generated by Django 2.2.6 on 2019-10-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input1', '0004_auto_20191027_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('School1', 's1'), ('DES', 's2'), ('ENG', 's3'), ('SCI', 's4'), ('M&C', 's5')], max_length=3),
        ),
    ]
