# Generated by Django 2.2.6 on 2019-10-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input1', '0005_auto_20191027_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input1.Branch'),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input1.Course'),
        ),
        migrations.AddField(
            model_name='booking',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input1.Department'),
        ),
        migrations.AddField(
            model_name='booking',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input1.Division'),
        ),
        migrations.AddField(
            model_name='booking',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input1.School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('Sc1', 's1'), ('DES', 's2'), ('ENG', 's3'), ('SCI', 's4'), ('M&C', 's5')], max_length=3),
        ),
    ]
