# Generated by Django 2.2.6 on 2019-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input1', '0006_auto_20191027_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='division',
            field=models.CharField(choices=[('A&L', 'b1'), ('DES', 'b2'), ('ENG', 'b3'), ('SCI', 'b4'), ('M&C', 'b5')], max_length=3),
        ),
    ]
