# Generated by Django 2.2.6 on 2019-10-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input1', '0007_auto_20191027_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input1.Division'),
        ),
    ]
