# Generated by Django 2.2.6 on 2019-10-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input1', '0008_auto_20191027_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='division',
            field=models.CharField(choices=[(1, 'AB-1'), (2, 'AB-2')], max_length=3, null=True),
        ),
    ]
