# Generated by Django 2.2.6 on 2019-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input1', '0013_auto_20191030_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='division',
            field=models.CharField(choices=[('A&L', 'Arts and Law'), ('DES', 'Design'), ('ENG', 'Engineering'), ('SCI', 'Science'), ('M&C', 'Management and Commerce')], max_length=3, null=True),
        ),
    ]
